# 网关Http服务器配置
ListenServer:
    # 默认Web服务
    Default:
        name: "web-server"
        # 服务器绑定地址
        address: "0.0.0.0:8080"
        # 设置TLS密钥文件地址
        tls-cret-file: ""
        tls-key-file: ""
        # 功能特性
        Features:
            # 设置限制请求Body大小，默认为 1M
            body-limit: "100K"
            # 设置请求压缩级别，可选 [NoCompression, BestSpeed, BestCompression, DefaultCompression, HuffmanOnly]；默认为 DefaultCompression
            gzip-level: "DefaultCompression"
            # 设置是否开启支持跨域访问特性，默认关闭
            cors-enable: true
            # 设置是否开启检查跨站请求伪造特性，默认关闭
            csrf-enable: true

    # 网关内部管理服务
    Admin:
        name: "manager-server"
        address: "0.0.0.0:9527"

# EndpointDiscovery 配置
EndpointDiscovery:
    # 默认为zookeeper，支持多注册中心。
    Zookeeper:
        endpoint-path: "/flux-endpoint"
        service-path: "/flux-service"
        # 启用的注册中心，默认default；其ID为下面多注册中心的key（不区分大小写）
        active-id: [ "default" ]
        # 支持多注册中心
        Default:
            address: "${zookeeper.address:172.16.248.132:2181}"
            timeout: "${zookeeper.timeout:5s}"
        QCloud:
            address: "${tx.zookeeper.address:172.16.248.133:2181}"
        HiCloud:
            address: "${hw.zookeeper.address:hw.zookeeper:2181}"

    # Resource 本地静态资源配置
    Resource:
        # 指定资源配置地址列表
        includes:
            - "./resources/echo.yml"
        endpoints:
        # 指定当前配置Endpoint列表
        services:
        # 指定当前配置Service列表

# BACKEND 配置参数
Backend:
    # Dubbo 协议后端服务配置
    Dubbo:
        # 集群策略：[Failover, Failfast, Failsafe/Failback, Available, Broadcast, Forking]
        cluster: "failover"
        # 负载策略: [Random, RoundRobin, LeastActive, ConsistentHash]
        load-balance: "random"
        # 日志开关；如果开启则打印Dubbo调用细节
        trace-enable: false
        # DuoobReference 初始化等待延时
        reference-delay: "30ms"
        # Dubbo注册中心列表
        Registry:
            id: "default"
            protocol: "zookeeper"
            timeout: "3s"
            address: "zookeeper.ifcode.net:2181"
            username: ""
            password: ""

    # Http协议后端服务配置
    Http:
        timeout: "10s"
        # 日志开关；如果开启则打印Dubbo调用细节
        trace-enable: false
