# 网关Http服务器配置
HttpWebServer:
    address: "0.0.0.0"
    port: 8080
    body-limit: "100K"
    #tls-cret-file: ""
    #tls-key-file: ""
    request-log-enable: true
    feature-debug-enable: true
    feature-echo-enable: true

# EndpointDiscovery 配置
EndpointDiscovery:
    # 默认为zookeeper，支持多注册中心。
    Zookeeper:
        endpoint-path: "/flux-endpoint"
        service-path: "/flux-service"
        # 启用的注册中心，默认default；其ID为下面多注册中心的key（不区分大小写）
        active-id:
            - "default"
            - "qcloud"
        # 支持多注册中心
        Default:
            address: "${zookeeper.address:zookeeper:2181}"
            timeout: "${zookeeper.timeout:5s}"
        QCloud:
            address: "${tx.zookeeper.address:tx.zookeeper:2181}"
        HiCloud:
            address: "${hw.zookeeper.address:hw.zookeeper:2181}"

    # Resource 本地静态资源配置
    Resource:
        # 指定资源配置地址列表
        includes:
            - "./resources/echo.yml"
        endpoints:
        # 指定当前配置Endpoint列表
        services:
        # 指定当前配置Service列表

# BACKEND 配置参数
Backend:
    # Dubbo 协议后端服务配置
    Dubbo:
        # 集群策略：[Failover, Failfast, Failsafe/Failback, Available, Broadcast, Forking]
        cluster: "failover"
        # 负载策略: [Random, RoundRobin, LeastActive, ConsistentHash]
        load-balance: "random"
        # 日志开关；如果开启则打印Dubbo调用细节
        trace-enable: false
        # DuoobReference 初始化等待延时
        reference-delay: "30ms"
        # Dubbo注册中心列表
        Registry:
            id: "default"
            protocol: "zookeeper"
            timeout: "3s"
            address: "zookeeper.ifcode.net:2181"
            username: ""
            password: ""

    # Http协议后端服务配置
    Http:
        timeout: "10s"
        # 日志开关；如果开启则打印Dubbo调用细节
        trace-enable: false
